
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[213] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   74,   72,
        1,    2,    1,   47,   56,   30,   42,   60,   48,   49,
       28,   26,   54,   27,   72,   29,   20,   55,   33,   39,
       35,   24,   24,   52,   53,   44,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   50,   43,   51,
       65,   63,   65,   64,   65,   71,   69,   71,   71,   68,
       66,   68,   68,    1,    2,   38,   40,   60,   59,    0,
       31,    0,    0,    0,    0,   32,   22,   21,    0,   58,
       57,   21,   20,   25,   25,   45,   34,   37,   36,   46,
       24,    0,   23,   24,   24,   24,   24,   24,   24,   24,

        7,   24,   24,   24,    3,   24,   24,   24,   24,   24,
       24,   41,   63,   62,    0,   61,   69,   70,   66,   67,
        0,    0,    0,    0,    0,   22,   22,    0,    0,   23,
       23,    0,   21,    0,   25,   25,    0,   21,   25,   23,
       23,   23,   24,   24,   24,   24,   24,   24,   24,   24,
        5,    9,   24,   24,   24,   24,   24,   22,   22,   22,
        0,   21,   23,   23,   23,   23,   23,   23,   23,   23,
       21,   25,   24,   16,   10,   24,   24,   24,    4,   24,
       24,   24,   24,   13,   24,   22,   22,   22,   23,   23,
       23,   23,    8,   24,   24,   24,   11,   24,   24,   24,

        6,   24,   24,   12,   24,   14,   15,   24,   17,   19,
       18,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   24,   37,   38,   24,   39,   40,   24,   41,
       42,   43,   24,   44,   45,   46,   47,   48,   49,   24,
       24,   24,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    2,    1,    3,    1,    1,    3,    1,
        1,    1,    4,    1,    4,    4,    1,    5,    6,    1,
        1,    1,    1,    6,    6,    1,    3,    1,    1,    6,
        5,    5,    6,    6,    6,    5,    6,    6,    6,    6,
        5,    6,    6,    5,    6,    5,    6,    5,    6,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[224] =
    {   0,
        0,    0,   50,   54,   58,   60,   62,   64,  349,  739,
       67,  739,   71,  319,  739,  739,  330,   67,  739,  739,
      739,   67,  739,   80,   88,   67,  101,  739,   66,  310,
       86,    0,  109,  739,  739,  739,  287,   98,   55,  290,
       70,   96,  285,  293,  271,  275,  274,  739,  259,  739,
      739,  739,  306,  739,  127,  739,  739,  305,  290,  739,
      739,  296,  135,  139,  739,  739,  739,   91,  739,    0,
      132,  140,  153,  161,  174,  182,  195,  203,  216,  739,
      739,  224,  237,  142,  245,  739,  739,  739,  739,  739,
        0,  258,  266,    0,    0,  261,  245,  258,  247,  251,

      239,  233,  233,  225,    0,  222,  229,  220,  227,  219,
      216,  739,  739,  739,  245,  739,  739,  739,  739,  739,
      244,  137,    0,  279,  287,  300,  308,  321,  329,  342,
      350,  363,  371,  384,  144,  163,  392,  139,  403,  410,
      418,  431,  215,  210,  200,  190,  202,  195,  191,  194,
        0,    0,  183,  176,  169,  178,  166,  439,  452,  460,
      473,  481,  494,  502,  515,  523,  536,  544,  557,  565,
      578,  586,  166,    0,    0,  166,  156,  162,    0,  148,
      145,  141,  151,    0,  148,  593,  601,  614,  622,  635,
      643,  656,    0,  132,  130,  114,    0,  102,   92,   84,

        0,   64,   32,    0,   18,    0,    0,   20,    0,    0,
        0,  739,  691,  697,  703,  709,  712,  714,  719,  724,
      728,  729,  733
    } ;

static const flex_int16_t yy_def[224] =
    {   0,
      212,    1,  213,  213,  214,  214,  215,  215,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  216,  212,  212,
      212,  212,  212,  212,  212,  212,  217,  212,  212,  212,
      212,  218,  218,  212,  212,  212,  218,  218,  218,   33,
      218,  218,  218,  218,  218,  218,  218,  212,  212,  212,
      212,  212,  212,  212,  219,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  220,  212,  221,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  217,  222,  222,  212,  212,  212,  212,  212,
      218,  212,  212,   33,   33,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  220,  223,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  222,  222,  212,   85,   85,  212,
      212,  212,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,   85,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  212,  212,  212,  212,  212,
      212,  212,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,    0,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212
    } ;

static const flex_int16_t yy_nxt[792] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   27,   28,
       29,   30,   31,   32,   33,   34,   10,   35,   36,   32,
       32,   37,   38,   39,   40,   41,   32,   42,   32,   32,
       32,   32,   43,   44,   45,   32,   32,   46,   47,   48,
       49,   50,   52,   53,  211,   54,   52,   53,  210,   54,
       57,   58,   57,   58,   61,   62,   61,   62,   64,   59,
       64,   59,   64,   65,   64,   69,   55,  209,   80,   71,
       55,   72,   73,   81,   74,   74,   86,   87,   63,  100,
       63,   75,   72,   70,   76,   73,  101,   74,   74,   69,

       72,   75,   72,   77,   75,   78,   78,   89,   90,  103,
      208,  104,   79,   72,   75,   72,   82,  123,   83,   83,
      207,   92,   79,   92,   93,   85,   94,   94,   97,  114,
      115,  105,  206,   95,   98,   85,  106,  120,  121,   99,
       64,  205,   64,   95,   72,   69,   72,   72,  204,   72,
       72,   92,   72,   92,   72,   72,   75,   72,   72,  135,
      135,  135,  135,  123,   75,   72,   75,   72,   77,  203,
      124,  124,  202,   72,   75,   72,   73,   75,   74,   74,
      135,  135,  201,  200,  199,   75,   92,   75,   92,   93,
      198,   92,   92,  197,   72,   75,   72,   72,  125,   72,

       72,  196,  195,  194,  193,  185,   75,  126,  125,  126,
      126,  184,  126,  126,  183,   72,   75,   72,   77,  127,
       78,   78,  182,  181,  180,  179,  178,  128,  129,  127,
      129,  130,  177,  131,  131,  176,   72,  128,   72,   77,
      132,  133,  133,  175,  174,  173,  120,  114,  134,   72,
      132,   72,   82,  157,   83,   83,  156,  137,  134,  137,
       93,   85,  138,  138,  155,  154,  153,  152,  151,  139,
       92,   85,   92,   93,  150,   92,   92,  149,  140,  139,
      140,  141,  125,  140,  140,  148,  147,  146,  145,  144,
      142,   72,  125,   72,   77,  143,  124,  124,  119,   92,

      142,   92,   93,   75,   92,   92,  118,  117,  113,  112,
      111,  125,  126,   75,  126,  126,  110,  126,  126,  109,
      158,  125,  158,  159,  127,  158,  158,  108,  107,  102,
       96,   88,  160,  161,  127,  161,   93,   67,  162,  162,
       66,  129,  160,  129,  130,  125,  131,  131,  212,  212,
      212,  212,  212,  132,  163,  125,  163,  164,  212,  165,
      165,  212,  167,  132,  167,  168,  166,  169,  169,  212,
      212,  212,  212,  212,  170,  129,  166,  129,  130,  212,
      131,  131,  212,   72,  170,   72,   77,  132,  133,  133,
      212,  212,  212,  212,  212,  134,  137,  132,  137,   93,

      212,  171,  171,  212,   92,  134,   92,   93,  125,  171,
      171,  212,  212,  212,  212,   92,  125,   92,  125,  212,
      172,  172,  140,  212,  140,  141,  125,  140,  140,  212,
      140,  212,  140,  141,  142,  140,  140,  212,  212,  212,
      212,  212,  142,  140,  142,  140,  141,  212,  140,  140,
      212,  158,  142,  158,  159,  142,  158,  158,  212,  212,
      212,  212,  212,  160,  186,  142,  186,  187,  212,  186,
      186,  212,  158,  160,  158,  159,  188,  158,  158,  212,
      212,  212,  212,  212,  160,   92,  188,   92,   93,  212,
      162,  162,  212,   92,  160,   92,   93,  125,  162,  162,

      212,  212,  212,  212,  212,  125,  163,  125,  163,  164,
      212,  165,  165,  212,  163,  125,  163,  164,  166,  165,
      165,  212,  212,  212,  212,  212,  166,  189,  166,  189,
      190,  212,  191,  191,  212,  163,  166,  163,  164,  192,
      165,  165,  212,  212,  212,  212,  212,  166,  167,  192,
      167,  168,  212,  169,  169,  212,  189,  166,  189,  190,
      170,  191,  191,  212,  212,  212,  212,  212,  192,  167,
      170,  167,  168,  212,  169,  169,  212,  167,  192,  167,
      168,  170,  169,  169,  212,  212,  212,  212,  212,  170,
       92,  170,   92,   93,  212,  171,  171,  212,   92,  170,

       92,  212,  125,  172,  172,  186,  212,  186,  187,  212,
      186,  186,  125,  186,  212,  186,  187,  188,  186,  186,
      212,  212,  212,  212,  212,  188,  186,  188,  186,  187,
      212,  186,  186,  212,  189,  188,  189,  190,  188,  191,
      191,  212,  212,  212,  212,  212,  192,  189,  188,  189,
      190,  212,  191,  191,  212,  189,  192,  189,  190,  192,
      191,  191,  212,  212,  212,  212,  212,  192,  189,  192,
      189,  190,  212,  191,  191,  212,  212,  192,  212,  212,
      192,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      192,   51,   51,   51,   51,   51,   51,   56,   56,   56,

       56,   56,   56,   60,   60,   60,   60,   60,   60,   68,
      212,   68,   68,   68,   68,   84,   84,   84,   91,   91,
      116,  116,  212,  116,  122,  212,  122,  122,  122,  122,
       68,  212,   68,  136,  136,  122,  212,  122,    9,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212

    } ;

static const flex_int16_t yy_chk[792] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,  208,    3,    4,    4,  205,    4,
        5,    5,    6,    6,    7,    7,    8,    8,   11,    5,
       11,    6,   13,   13,   13,   18,    3,  203,   26,   22,
        4,   22,   22,   26,   22,   22,   29,   29,    7,   39,
        8,   22,   24,   18,   24,   24,   39,   24,   24,   68,

       25,   22,   25,   25,   24,   25,   25,   31,   31,   41,
      202,   41,   25,   27,   24,   27,   27,   68,   27,   27,
      200,   33,   25,   33,   33,   27,   33,   33,   38,   55,
       55,   42,  199,   33,   38,   27,   42,   63,   63,   38,
       64,  198,   64,   33,   71,  122,   71,   71,  196,   71,
       71,  138,   72,  138,   72,   72,   71,   72,   72,   84,
       84,  135,  135,  122,   72,   73,   71,   73,   73,  195,
       73,   73,  194,   74,   72,   74,   74,   73,   74,   74,
      136,  136,  185,  183,  182,   74,   75,   73,   75,   75,
      181,   75,   75,  180,   76,   74,   76,   76,   75,   76,

       76,  178,  177,  176,  173,  157,   76,   77,   75,   77,
       77,  156,   77,   77,  155,   78,   76,   78,   78,   77,
       78,   78,  154,  153,  150,  149,  148,   78,   79,   77,
       79,   79,  147,   79,   79,  146,   82,   78,   82,   82,
       79,   82,   82,  145,  144,  143,  121,  115,   82,   83,
       79,   83,   83,  111,   83,   83,  110,   85,   82,   85,
       85,   83,   85,   85,  109,  108,  107,  106,  104,   85,
       92,   83,   92,   92,  103,   92,   92,  102,   93,   85,
       93,   93,   92,   93,   93,  101,  100,   99,   98,   97,
       93,  124,   92,  124,  124,   96,  124,  124,   62,  125,

       93,  125,  125,  124,  125,  125,   59,   58,   53,   49,
       47,  125,  126,  124,  126,  126,   46,  126,  126,   45,
      127,  125,  127,  127,  126,  127,  127,   44,   43,   40,
       37,   30,  127,  128,  126,  128,  128,   17,  128,  128,
       14,  129,  127,  129,  129,  128,  129,  129,    9,    0,
        0,    0,    0,  129,  130,  128,  130,  130,    0,  130,
      130,    0,  131,  129,  131,  131,  130,  131,  131,    0,
        0,    0,    0,    0,  131,  132,  130,  132,  132,    0,
      132,  132,    0,  133,  131,  133,  133,  132,  133,  133,
        0,    0,    0,    0,    0,  133,  134,  132,  134,  134,

        0,  134,  134,    0,  137,  133,  137,  137,  134,  137,
      137,    0,    0,    0,    0,  139,  137,  139,  134,    0,
      139,  139,  140,    0,  140,  140,  137,  140,  140,    0,
      141,    0,  141,  141,  140,  141,  141,    0,    0,    0,
        0,    0,  141,  142,  140,  142,  142,    0,  142,  142,
        0,  158,  141,  158,  158,  142,  158,  158,    0,    0,
        0,    0,    0,  158,  159,  142,  159,  159,    0,  159,
      159,    0,  160,  158,  160,  160,  159,  160,  160,    0,
        0,    0,    0,    0,  160,  161,  159,  161,  161,    0,
      161,  161,    0,  162,  160,  162,  162,  161,  162,  162,

        0,    0,    0,    0,    0,  162,  163,  161,  163,  163,
        0,  163,  163,    0,  164,  162,  164,  164,  163,  164,
      164,    0,    0,    0,    0,    0,  164,  165,  163,  165,
      165,    0,  165,  165,    0,  166,  164,  166,  166,  165,
      166,  166,    0,    0,    0,    0,    0,  166,  167,  165,
      167,  167,    0,  167,  167,    0,  168,  166,  168,  168,
      167,  168,  168,    0,    0,    0,    0,    0,  168,  169,
      167,  169,  169,    0,  169,  169,    0,  170,  168,  170,
      170,  169,  170,  170,    0,    0,    0,    0,    0,  170,
      171,  169,  171,  171,    0,  171,  171,    0,  172,  170,

      172,    0,  171,  172,  172,  186,    0,  186,  186,    0,
      186,  186,  171,  187,    0,  187,  187,  186,  187,  187,
        0,    0,    0,    0,    0,  187,  188,  186,  188,  188,
        0,  188,  188,    0,  189,  187,  189,  189,  188,  189,
      189,    0,    0,    0,    0,    0,  189,  190,  188,  190,
      190,    0,  190,  190,    0,  191,  189,  191,  191,  190,
      191,  191,    0,    0,    0,    0,    0,  191,  192,  190,
      192,  192,    0,  192,  192,    0,    0,  191,    0,    0,
      192,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      192,  213,  213,  213,  213,  213,  213,  214,  214,  214,

      214,  214,  214,  215,  215,  215,  215,  215,  215,  216,
        0,  216,  216,  216,  216,  217,  217,  217,  218,  218,
      219,  219,    0,  219,  220,    0,  220,  220,  220,  220,
      221,    0,  221,  222,  222,  223,    0,  223,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2005076.l"



#line 8 "2005076.l"
	
#include <cstdio>
#include <cstdlib>
#include <vector>
#include "symbol_table.h"
#include "y.tab.h"
#include "utilities.h"

using namespace std;

extern SymbolTable* sym;
int line_count = 1;
int error_count = 0;

extern ofstream logout;
extern YYSTYPE yylval;

// if a string stretches multiple lines, we need to show the starting line no in case of token printing, 
// hence we need to keep the line no. unchanged while the string is running
int inside_line = 0; 

// in case of printing character and strings, if it is unfinished then we print
// characters like \n \b as they are (not their original behaviour), but if they are 
// completed properly, then \n will be replaced by NEWLINE...

string cur_char;
string cur_string, cur_string_raw;
string cur_comment;
int char_len; // will hold the length of the original one, not raw one

SymbolInfo* generate_token_class(const string& name, const string& type, const string& token_name) {
	SymbolInfo* res = new SymbolInfo(name, type);
	string str = token_name + " : " + name;
	res->set_rule(str);
	res->set_terminal(true);
	res->set_line(line_count, line_count); // start end same line for terminal
	return res;
}

char generate_special_character(char c) {
	// MISC [ntafbvr0\'\"\\]
	if (c == 'n') return '\n';
	else if (c == 't') return '\t';
	else if (c == 'a') return '\a';
	else if (c == 'f') return '\f';
	else if (c == 'b') return '\b';
	else if (c == 'v') return '\v';
	else if (c == 'r') return '\r';
	else if (c == '0') return '\0';
	else return c;
}

void reset(reset_type rt) {
	inside_line = 0;
	if (rt == CHAR_RESET) {
		cur_char.clear();
		char_len = 0;
	}
	else if (rt == STRING_RESET) {
		cur_string.clear();
		cur_string_raw.clear();
	}
	else if (rt == COMMENT_RESET) {
		cur_comment.clear();
	}
}

string capitalize(const string& s) {
	string ret = s;
	for (char& c : ret) c = toupper(c);
	return ret;
}

string get_real_string(string ss) {
    string ret = "";
    const int sz = ss.size();
    for (int i = 0; i < sz; i++) {
        if (ss[i] != '\\') {
            ret += ss[i];
        }
        else {
            if (i == sz - 1) {
                cerr << "this should not happen!";
                ret += ss[i];
            }
            else {
                char cc = generate_special_character(ss[i + 1]);
                if (cc == ss[i + 1]) {
                    ret += ss.substr(i, 2);
                }
                else {
                    ret += cc;
                }
                i++;
            }
        }
    }
    return ret;
}

void printKeyword() {
	string cap = capitalize(yytext);
	// // tokenout << "<" << cap << ", " << yytext << ">" << endl;
	logout << "Line# " << line_count << ": Token <" << cap << "> Lexeme " << yytext << " found" << endl;
}

void printIdentifier() {
	logout << "Line# " << line_count << ": Token <ID> Lexeme " << yytext << " found" << endl;
	// tokenout << "<ID, " << yytext << ">" << endl;
	// bool success = sym->insert(yytext, "ID", logout);
	// if (success) sym->print('A', logout);
}

void printNum(num_type nt, const string& str) {
	// if (str[0] == '+' || str[0] == '-') {
	// 	for (int i = 1; i < str.size(); i++) str[i - 1] = str[i];
	// 	str.pop_back();
	// }
	if (nt == INTNUM) {
		// tokenout << "<CONST_INT, " << str << ">" << endl;
		logout << "Line# " << line_count << ": Token <CONST_INT> Lexeme " << str << " found" << endl;
	}
	else if (nt == FLOATNUM) {
		// tokenout << "<CONST_FLOAT, " << str << ">" << endl;
		logout << "Line# " << line_count << ": Token <CONST_FLOAT> Lexeme " << str << " found" << endl;
	}
}

void printOpPunc(const string& token) {
	// tokenout << "<" << token << ", " << yytext << ">" << endl;
	logout << "Line# " << line_count << ": Token <" << token << "> Lexeme " << yytext << " found" << endl;	
}

void printChar(const string& str) {
	// tokenout << "<CONST_CHAR, " << str << ">" << endl;
	logout << "Line# " << line_count << ": Token <CONST_CHAR> Lexeme " << str << " found" << endl;
}

void printString(line_type lt, const string& str1, const string& str2) {
	if (lt == SINGLE_LINE) {
		logout << "Line# " << line_count << ": Token <SINGLE LINE STRING> Lexeme " << str1 << " found" << endl;
		// tokenout << "<SINGLE LINE STRING, " << str2 << ">" << endl; 
	}
	else if (lt == MULTILINE) {
		logout << "Line# " << line_count << ": Token <MULTI LINE STRING> Lexeme " << str1 << " found" << endl;
		// tokenout << "<MULTI LINE STRING, " << str2 << ">" << endl;
	}
}

void printComment(line_type lt, const string& str) {
	if (lt == SINGLE_LINE) {
		logout << "Line# " << line_count << ": Token <SINGLE LINE COMMENT> Lexeme " << str << " found" << endl;
	}
	else if (lt == MULTILINE) {
		logout << "Line# " << line_count << ": Token <MULTI LINE COMMENT> Lexeme " << str << " found" << endl;
	}
}

#line 856 "lex.yy.c"
#line 857 "lex.yy.c"

#define INITIAL 0
#define STATE_STRING 1
#define C_COMMENT 2
#define CPP_COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 192 "2005076.l"


#line 1080 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 213 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 739 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 194 "2005076.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 195 "2005076.l"
{ 
							line_count++; 
						}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 199 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return IF;
						}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 204 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return ELSE;
						}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 209 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return FOR;
						}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 214 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return WHILE;
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 219 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return DO;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 224 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return BREAK;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 229 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return INT;
						}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 234 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return CHAR;
						}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 239 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return FLOAT;
						}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 244 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return DOUBLE;
						}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 249 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return VOID;
						}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 254 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return RETURN;
						}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 259 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return SWITCH;
						}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 264 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return CASE;
						}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 269 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return DEFAULT;
						}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 274 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return CONTINUE;
						}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 279 "2005076.l"
{
							printKeyword();
							yylval.symbol_info = generate_token_class(yytext, "KEYWORD", capitalize(yytext));
							return PRINTLN;
						}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 286 "2005076.l"
{ 
							printNum(INTNUM, yytext); 
							yylval.symbol_info = new SymbolInfo(yytext, "CONST_INT", "int");
							yylval.symbol_info->set_line(line_count, line_count);
							yylval.symbol_info->set_terminal(true);
							string str = "CONST_INT : ";
							str += yytext;
							yylval.symbol_info->set_rule(str);
							return CONST_INT;
						}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 296 "2005076.l"
{ 
							printNum(FLOATNUM, yytext); 
							yylval.symbol_info = new SymbolInfo(yytext, "CONST_FLOAT", "float");
							yylval.symbol_info->set_line(line_count, line_count);
							yylval.symbol_info->set_terminal(true);
							string str = "CONST_FLOAT : ";
							str += yytext;
							yylval.symbol_info->set_rule(str);
							return CONST_FLOAT;
 						}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 306 "2005076.l"
{ 
							show_error(LEXICAL, TOO_DECIMAL, yytext, logout); 
						}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 309 "2005076.l"
{ 
							show_error(LEXICAL, ILL_FORMED, yytext, logout); 
						}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 314 "2005076.l"
{ 
							printIdentifier(); 
							yylval.symbol_info = new SymbolInfo(yytext, "ID"); // if it is a variable declaration, set its data type field in parser.y and use that
							yylval.symbol_info->set_line(line_count, line_count);
							yylval.symbol_info->set_terminal(true);
							string str = "ID : ";
							str += yytext;
							yylval.symbol_info->set_rule(str);
							return ID;
						}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 324 "2005076.l"
{ 
							show_error(LEXICAL, INVALID_SUFFIX, yytext, logout); 
						}
	YY_BREAK
case 26:
#line 330 "2005076.l"
case 27:
YY_RULE_SETUP
#line 330 "2005076.l"
{ 	printOpPunc("ADDOP");
							yylval.symbol_info = generate_token_class(yytext, "ADDOP", "ADDOP");
							return ADDOP;
						}
	YY_BREAK
case 28:
#line 335 "2005076.l"
case 29:
#line 336 "2005076.l"
case 30:
YY_RULE_SETUP
#line 336 "2005076.l"
{ 	printOpPunc("MULOP");
							yylval.symbol_info = generate_token_class(yytext, "MULOP", "MULOP");
							return MULOP;
						}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 340 "2005076.l"
{ 	printOpPunc("INCOP");
							yylval.symbol_info = generate_token_class(yytext, "INCOP", "INCOP");
							return INCOP;
						}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 344 "2005076.l"
{ 	printOpPunc("DECOP");
							yylval.symbol_info = generate_token_class(yytext, "DECOP", "DECOP");
							return DECOP;
						}
	YY_BREAK
case 33:
#line 349 "2005076.l"
case 34:
#line 350 "2005076.l"
case 35:
#line 351 "2005076.l"
case 36:
#line 352 "2005076.l"
case 37:
#line 353 "2005076.l"
case 38:
YY_RULE_SETUP
#line 353 "2005076.l"
{ 	printOpPunc("RELOP");
							yylval.symbol_info = generate_token_class(yytext, "RELOP", "RELOP");
							return RELOP;
						}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 357 "2005076.l"
{ 	printOpPunc("ASSIGNOP");
							yylval.symbol_info = generate_token_class(yytext, "ASSIGNOP", "ASSIGNOP");
							return ASSIGNOP;
						}
	YY_BREAK
case 40:
#line 362 "2005076.l"
case 41:
YY_RULE_SETUP
#line 362 "2005076.l"
{ 	printOpPunc("LOGICOP");
							yylval.symbol_info = generate_token_class(yytext, "LOGICOP", "LOGICOP");
							return LOGICOP;
						}
	YY_BREAK
case 42:
#line 367 "2005076.l"
case 43:
#line 368 "2005076.l"
case 44:
#line 369 "2005076.l"
case 45:
#line 370 "2005076.l"
case 46:
YY_RULE_SETUP
#line 370 "2005076.l"
{ 	printOpPunc("BITOP");
							yylval.symbol_info = generate_token_class(yytext, "BITOP", "BITOP");
							return BITOP;
						}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 374 "2005076.l"
{ 	printOpPunc("NOT");
							yylval.symbol_info = generate_token_class(yytext, "NOT", "NOT");
							return NOT;
						}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 378 "2005076.l"
{ 	printOpPunc("LPAREN");
							yylval.symbol_info = generate_token_class(yytext, "LPAREN", "LPAREN");
							return LPAREN;
						}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 382 "2005076.l"
{ 	printOpPunc("RPAREN");
							yylval.symbol_info = generate_token_class(yytext, "RPAREN", "RPAREN");
							return RPAREN;
						}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 386 "2005076.l"
{ 	printOpPunc("LCURL");
							yylval.symbol_info = generate_token_class(yytext, "LCURL", "LCURL");
							return LCURL;
						}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 390 "2005076.l"
{ 	printOpPunc("RCURL");
							yylval.symbol_info = generate_token_class(yytext, "RCURL", "RCURL");
							return RCURL;
						}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 394 "2005076.l"
{ 	printOpPunc("LSQUARE");
							yylval.symbol_info = generate_token_class(yytext, "LSQUARE", "LSQUARE");
							return LSQUARE;
						}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 398 "2005076.l"
{ 	printOpPunc("RSQUARE");
							yylval.symbol_info = generate_token_class(yytext, "RSQUARE", "RSQUARE");
							return RSQUARE;
						}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 402 "2005076.l"
{ 	printOpPunc("COMMA");
							yylval.symbol_info = generate_token_class(yytext, "COMMA", "COMMA");
							return COMMA;
						}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 406 "2005076.l"
{ 	printOpPunc("SEMICOLON");
							yylval.symbol_info = generate_token_class(yytext, "SEMICOLON", "SEMICOLON");
							return SEMICOLON;
						}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 412 "2005076.l"
{ 
							BEGIN STATE_STRING; 
							reset(STRING_RESET); 
						}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 416 "2005076.l"
{ 
							BEGIN CPP_COMMENT; 
							reset(COMMENT_RESET); 
						}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 420 "2005076.l"
{ 
							BEGIN C_COMMENT; 
							reset(COMMENT_RESET); 
						}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 426 "2005076.l"
{
                            string str = yytext;
                            str.erase(str.begin());
                            str.pop_back(); // removed first and last '
                            cur_char = get_real_string(str);
                            char_len = cur_char.size();
                            if (char_len == 0) {
                                show_error(LEXICAL, EMPTY_CHAR, "\'\'", logout);
                            }
                            else if (char_len > 1) {
                                str = "\'" + str + "\'";
                                show_error(LEXICAL, MULTICHAR, str, logout);
                            }
                            else printChar(cur_char);
                        }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 441 "2005076.l"
{
                            string str = yytext;
                            str.erase(str.begin()); // removed first '
                            cur_char = get_real_string(str);
                            char_len = cur_char.size();
                            str = "\'" + str;
                            show_error(LEXICAL, UNFINISHED_CHAR, str, logout);
                            if (yytext[yyleng - 1] == '\n') line_count++;
                        }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 452 "2005076.l"
{ 
							cur_string += generate_special_character(yytext[yyleng - 1]); 
							cur_string_raw += yytext; 
						}
	YY_BREAK
case YY_STATE_EOF(STATE_STRING):
#line 456 "2005076.l"
{
							// if error, print the raw version
							string str = "\"" + cur_string_raw;
							line_count += inside_line;
							show_error(LEXICAL, UNFINISHED_STRING, str, logout);
							BEGIN INITIAL;
						}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 463 "2005076.l"
{ 
							// an example comment like this: 
							//"abc\
							def"
							// not adding to cur_string, as multiline string ultimately is not multiline
							// the aforementioned string is actually "abcdef"
							// so only add to raw string
							inside_line++; 
							cur_string_raw += yytext;
						}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 472 "2005076.l"
{
							// error as multiline string must have '\' at the end of a line
							// if error, print the raw version
							string str = "\"" + cur_string_raw;
							line_count += inside_line;
							show_error(LEXICAL, UNFINISHED_STRING, str, logout);
							line_count++;
							BEGIN INITIAL; 
						}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 481 "2005076.l"
{
							// print the raw version to log file
							// and the original one to token file
							string str = "\"" + cur_string_raw + "\"";
							string str2 = cur_string;
							if (inside_line == 0) printString(SINGLE_LINE, str, str2);
							else printString(MULTILINE, str, str2);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 491 "2005076.l"
{ 	cur_string += yytext[0]; 
							cur_string_raw += yytext[0]; 
						}
	YY_BREAK
case YY_STATE_EOF(CPP_COMMENT):
#line 496 "2005076.l"
{
							string str = "//" + cur_comment;
							printComment(SINGLE_LINE, str);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 502 "2005076.l"
{
							inside_line++;
							string str = "//" + cur_comment;
							printComment(SINGLE_LINE, str);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 509 "2005076.l"
{ 
							inside_line++; 
							cur_comment += yytext; 
						}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 513 "2005076.l"
{ 
							cur_comment += yytext[0]; 
						}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 518 "2005076.l"
{ 
							inside_line++; 
							cur_comment += yytext; 
						}
	YY_BREAK
case YY_STATE_EOF(C_COMMENT):
#line 522 "2005076.l"
{
							string str = "/*" + cur_comment;
							line_count += inside_line;
							show_error(LEXICAL, UNFINISHED_COMMENT, str, logout);
							BEGIN INITIAL;
						}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 528 "2005076.l"
{
							string str = "/*" + cur_comment + "*/";
							printComment(MULTILINE, str);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 534 "2005076.l"
{ 
							cur_comment += yytext[0]; 
						}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 539 "2005076.l"
{ return 0; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 540 "2005076.l"
{ show_error(LEXICAL, UNRECOGNIZED, yytext, logout); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 542 "2005076.l"
ECHO;
	YY_BREAK
#line 1738 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 213 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 213 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 212);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 542 "2005076.l"

