--Triggers
create sequence user_seq;

create or replace trigger person_insert_trig
   before insert on PERSON
   for each row
begin
   if :new.PERSON_ID is null then
      :new.PERSON_ID := user_seq.nextval;
   end if;
end;
/


--Functions

create or replace FUNCTION IS_VALID_USER_INSERT(USERNAME IN VARCHAR2, UEMAIL IN VARCHAR2)
return BOOLEAN IS
	COUNTER NUMBER;
	COUNTER2 NUMBER;
BEGIN
	SELECT COUNT(*) INTO COUNTER FROM "USER" WHERE USER_NAME = USERNAME;
	IF COUNTER = 0 THEN
		SELECT COUNT(*) INTO COUNTER2 FROM PERSON WHERE EMAIL = UEMAIL;
		IF COUNTER2 = 0 THEN
			RETURN TRUE;
		ELSE
			RETURN FALSE;
		END IF;
	ELSE 
		RETURN FALSE;
	END IF;
END;
/

create or replace FUNCTION IS_VALID_ADMIN_INSERT(USERNAME IN VARCHAR2, UEMAIL IN VARCHAR2)
return BOOLEAN IS
	COUNTER NUMBER;
	COUNTER2 NUMBER;
BEGIN
	SELECT COUNT(*) INTO COUNTER FROM ADMIN WHERE ADMIN_NAME = USERNAME;
	IF COUNTER = 0 THEN
		SELECT COUNT(*) INTO COUNTER2 FROM PERSON WHERE EMAIL = UEMAIL;
		IF COUNTER2 = 0 THEN
			RETURN TRUE;
		ELSE
			RETURN FALSE;
		END IF;
	ELSE 
		RETURN FALSE;
	END IF;
END;
/



-- procedures

CREATE OR REPLACE PROCEDURE INSERT_USER(FN IN VARCHAR2, LN IN VARCHAR2, AD IN VARCHAR2, EM IN VARCHAR2, PH_NUM IN VARCHAR2, DET IN VARCHAR2, UN IN VARCHAR2, PW IN VARCHAR2) 
IS
	ID NUMBER;
BEGIN
	IF IS_VALID_USER_INSERT(UN, EM) THEN
		INSERT INTO "PERSON" ("FIRST_NAME", "LAST_NAME", "ADDRESS", "EMAIL", "PHONE_NUMBER", "DETAILS") VALUES (FN, LN, AD, EM, PH_NUM, DET);
		select user_seq.currval into ID from DUAL;
		INSERT INTO "USER" ("PERSON_ID", "USER_NAME", "PASSWORD") VALUES (ID, UN, PW);
	ELSE
		raise_application_error(-20111,'USERNAME OR EMAIL IS NOT UNIQUE');
	END IF;
END ;
/



CREATE OR REPLACE PROCEDURE INSERT_ADMIN(FN IN VARCHAR2, LN IN VARCHAR2, AD IN VARCHAR2, EM IN VARCHAR2, PH_NUM IN VARCHAR2, DET IN VARCHAR2, AN IN VARCHAR2, PW IN VARCHAR2) 
IS
	ID NUMBER;
BEGIN
	IF IS_VALID_ADMIN_INSERT(AN, EM) THEN
		INSERT INTO "PERSON" ("FIRST_NAME", "LAST_NAME", "ADDRESS", "EMAIL", "PHONE_NUMBER", "DETAILS") VALUES (FN, LN, AD, EM, PH_NUM, DET);
		select user_seq.currval into ID from DUAL;
		INSERT INTO "ADMIN" ("PERSON_ID", "ADMIN_NAME", "PASSWORD") VALUES (ID, AN, PW);
	ELSE
		raise_application_error(-20111,'ADMIN_NAME OR EMAIL IS NOT UNIQUE');
	END IF;
END ;
/

CREATE OR REPLACE PROCEDURE UPDATE_USER(A_ID IN VARCHAR2, A_FIRST_NAME IN VARCHAR2, A_LAST_NAME IN VARCHAR2, A_ADDRESS IN VARCHAR2, A_EMAIL IN VARCHAR2, A_PHONE_NUMBER IN VARCHAR2, A_DETAILS IN VARCHAR2) IS 
BEGIN 
	IF (IS_VALID_UPDATE_USER(A_ID, A_EMAIL)) THEN
		UPDATE PERSON
		SET FIRST_NAME = A_FIRST_NAME, LAST_NAME = A_LAST_NAME, ADDRESS = A_ADDRESS, EMAIL = A_EMAIL, PHONE_NUMBER = A_PHONE_NUMBER, DETAILS = A_DETAILS
		WHERE PERSON_ID = A_ID;
	ELSE 
		raise_application_error(-20111,'USER CANNOT BE UPDATED');
	END IF;
END;
/



CREATE OR REPLACE PROCEDURE UPDATE_ADMIN(A_ID IN VARCHAR2, A_FIRST_NAME IN VARCHAR2, A_LAST_NAME IN VARCHAR2, A_ADDRESS IN VARCHAR2, A_EMAIL IN VARCHAR2, A_PHONE_NUMBER IN VARCHAR2, A_DETAILS IN VARCHAR2) IS 
BEGIN 
	IF (IS_VALID_UPDATE_ADMIN(A_ID, A_EMAIL)) THEN
		UPDATE PERSON
		SET FIRST_NAME = A_FIRST_NAME, LAST_NAME = A_LAST_NAME, ADDRESS = A_ADDRESS, EMAIL = A_EMAIL, PHONE_NUMBER = A_PHONE_NUMBER, DETAILS = A_DETAILS
		WHERE PERSON_ID = A_ID;
	ELSE 
		raise_application_error(-20111,'ADMIN CANNOT BE UPDATED');
	END IF;
END;
/