--DROP TABLE PERSON;
CREATE TABLE PERSON (
	PERSON_ID		VARCHAR2(15) NOT NULL,
	FIRST_NAME		VARCHAR2(20) NOT NULL,
	LAST_NAME		VARCHAR2(20) NOT NULL,
	ADDRESS			VARCHAR2(100),
    DATE_OF_BIRTH   DATE,
	BLOOD_GROUP		VARCHAR2(15),
	EMAIL			VARCHAR2(100) NOT NULL,
	PHONE_NUMBER 	VARCHAR2(14),
	DETAILS			VARCHAR2(1000),
    		
	PRIMARY KEY (PERSON_ID)
);


--DROP TABLE ADMIN;
CREATE TABLE ADMIN (
	PERSON_ID       VARCHAR2(15)  NOT NULL,
	ADMIN_NAME		VARCHAR2(20)  NOT NULL,
	PASSWORD		VARCHAR2(200)  NOT NULL,		
	PRIMARY KEY (PERSON_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON
);

--DROP TABLE "USER";
CREATE TABLE "USER"(
    PERSON_ID       VARCHAR2(15)  NOT NULL,
    USER_NAME       VARCHAR2(25) NOT NULL,
    PASSWORD        VARCHAR2(200) NOT NULL,
    PRIMARY KEY(PERSON_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON 
);

